[tool.black]
line-length = 110
target-version = ["py38"]
skip-string-normalization = true

[tool.mypy]
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov mockproj --cov-report term-missing --cov-fail-under 100"
# filterwarnings = [
#     "ignore::DeprecationWarning",
# ]

# [tool.coverage.run]
# omit = [
#     "myproj/mysubmodule/*"
# ]
