---
name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install packages with pipenv
        run: |
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install pipenv
          pipenv sync --dev --system
      - uses: pre-commit/action@v3.0.0
